security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:

        # Debug toolbar Symfony - не чіпаємо
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Login endpoint
        login:
            pattern: ^/auth/login
            stateless: true
            json_login:
                check_path: /auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Main protected API
        main:
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        # Login + register не потребує токена
        - { path: ^/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/auth/register, roles: PUBLIC_ACCESS }

        # Все інше закрито
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
